Repository Y-CHILDREN/client, pull requests merged in 2024-11, with the labels that each got.

#5 로그인 컴포넌트 생성
  src/App.tsx
  src/core/presentation/assets/loginPage/Google Logo.svg
  src/core/presentation/assets/loginPage/logo-kakao.svg
  src/core/presentation/assets/loginPage/logo-naver.svg
  src/core/presentation/components/layout/LoginLayout.tsx
  src/core/presentation/pages/Login.css
  src/core/presentation/pages/Login.tsx
  tailwind.config.js
Labels: 🖊️ feature

#15 마이 페이지 컴포넌트 생성
  .gitignore
  package.json
  src/App.tsx
  src/core/domain/entities/entitiy.tsx
  src/core/presentation/assets/mypage/Group.png
  src/core/presentation/assets/mypage/Group2.png
  src/core/presentation/assets/mypage/share.svg
  src/core/presentation/assets/mypage/tripIcon.png
  src/core/presentation/assets/mypage/user.svg
  src/core/presentation/assets/navigation/House.svg
  src/core/presentation/assets/navigation/SuitcaseRolling.svg
  src/core/presentation/assets/navigation/User.svg
  src/core/presentation/components/layout/Footer.tsx
  src/core/presentation/components/layout/Header.tsx
  src/core/presentation/components/layout/Layout.css
  src/core/presentation/components/layout/Layout.tsx
  src/core/presentation/components/layout/LoginLayout.tsx
  src/core/presentation/pages/Login.tsx
  src/core/presentation/pages/Mypage.tsx
  tailwind.config.js
Labels: 🖊️ feature

#36 내 여행 페이지 생성
  src/App.tsx
  src/core/data/infrastructure/services/service.tsx
  src/core/data/infrastructure/services/userRepositoryImpl.ts
  src/core/domain/entities/entitiy.tsx
  src/core/domain/entities/user.ts
  src/core/domain/entities/userRepository.ts
  src/core/presentation/assets/mytrips/tripCardImage.png
  src/core/presentation/components/TripCard.tsx
  src/core/presentation/components/layout/Layout.css
  src/core/presentation/components/layout/LoginLayout.tsx
  src/core/presentation/hooks/stores/authStore.ts
  src/core/presentation/pages/Login.tsx
  src/core/presentation/pages/Mypage.tsx
  src/core/presentation/pages/Mytrips.tsx
Labels: 🖊️ feature

#37 마이 페이지 api 적용
  src/core/data/infrastructure/services/userRepositoryImpl.ts
  src/core/domain/entities/userRepository.ts
  src/core/presentation/hooks/stores/authStore.ts
  src/core/presentation/pages/Login.tsx
  src/core/presentation/pages/Mypage.tsx
Labels: 🖊️ feature

#11 feat: add Member to CreateTrip
  src/core/presentation/components/Search/SearchInputComponent.stories.tsx
  src/core/presentation/components/Search/SearchInputComponent.tsx
  src/core/presentation/components/createTrip/CreateTrip.tsx
  src/core/presentation/components/datePicker/DatePickerComponent.stories.ts
  src/core/presentation/components/dropDown/MultiSelectDropDown.tsx
  src/core/presentation/hooks/stores/tripStore.ts
  src/core/presentation/hooks/useDebounce.ts
Labels: 🖊️ feature

#38 refactor : 유저 로그인 시 유저의 정보를 불러오는 로직 변경
  src/App.tsx
  src/core/presentation/components/auth/AuthProvider.tsx
  src/core/presentation/hooks/stores/authStore.ts
  src/core/presentation/pages/Mypage.tsx
  src/routers/ProtectedRouter.tsx
Labels: ♻️ refactor

#39 feat : 회원 탈퇴 확인하는 페이지 추가
  src/App.tsx
  src/core/presentation/assets/deleteCompletePage/byebye.gif
  src/core/presentation/assets/navigation/House.svg
  src/core/presentation/assets/navigation/offHouse.svg
  src/core/presentation/assets/navigation/offSuitcaseRolling.svg
  src/core/presentation/assets/navigation/offUser.svg
  src/core/presentation/assets/navigation/onHouse.svg
  src/core/presentation/assets/navigation/onSuitcaseRolling.svg
  src/core/presentation/assets/navigation/onUser.svg
  src/core/presentation/assets/react.svg
  src/core/presentation/components/createTrip/CreateTrip.tsx
  src/core/presentation/components/layout/Footer.tsx
  src/core/presentation/pages/DeleteCompletePage.tsx
  src/core/presentation/pages/Mypage.tsx
Labels: 🖊️ feature

#40 [여행 일정] DatePicker CSS
  package.json
  pnpm-lock.yaml
  src/core/presentation/components/createTrip/CreateTrip.tsx
  src/core/presentation/components/datePicker/DatePickerComponent.tsx
Labels: 🖊️ feature

#42 [일정 생성] CSS & Search component
  package.json
  pnpm-lock.yaml
  src/core/domain/entities/regions.ts
  src/core/domain/entities/trip.ts
  src/core/presentation/components/Search/SearchInputComponent.tsx
  src/core/presentation/components/createTrip/CreateTrip.tsx
  src/core/presentation/components/dropDown/DropDown.tsx
  src/core/presentation/components/dropDown/MultiSelectDropDown.tsx
  src/core/presentation/pages/CreateTripPage.tsx
Labels: 🖊️ feature

#44 스타일 수정
  src/core/data/infrastructure/services/userService.ts
  src/core/presentation/assets/loginPage/backGoundImg.png
  src/core/presentation/components/auth/AuthProvider.tsx
  src/core/presentation/components/layout/LoginLayout.tsx
  src/core/presentation/pages/Login.tsx
  src/core/presentation/pages/Mypage.tsx
  src/core/presentation/pages/Mytrips.tsx
Labels: ♻️ refactor

#46 [여행 디테일] TripDetailPage (기본 ver.)
  src/core/domain/entities/trip.ts
  src/core/presentation/components/TripDetail.tsx
  src/core/presentation/components/createTrip/CreateTrip.tsx
  src/core/presentation/pages/TripDetailPage.tsx
Labels: 🖊️ feature

#47 feat : 이미지 경로 변경 및 내여행 api 연결하여 진행 상활별 여행 카드 분류, 토큰이 있는 상태에서는 로그인 유지되도록 수정
  package.json
  public/assets/deleteCompletePage/byebye.gif
  public/assets/home/Busan.jpeg
  public/assets/home/China.jpg
  public/assets/home/Japan.jpeg
  public/assets/home/Jeju.jpg
  public/assets/home/LA.jpg
  public/assets/home/Picture1.png
  public/assets/home/Seoul.jpg
  public/assets/home/beach.png
  public/assets/loginPage/GoogleLogo.svg
  public/assets/loginPage/backGroundImg.png
  public/assets/loginPage/logo-kakao.svg
  public/assets/loginPage/logo-naver.svg
  public/assets/mypage/Group.png
  public/assets/mypage/Group2.png
  public/assets/mypage/share.svg
  public/assets/mypage/tripIcon.png
  public/assets/mypage/user.svg
  public/assets/mytrips/tripCardImage.png
  public/assets/navigation/offHouse.svg
  public/assets/navigation/offSuitcaseRolling.svg
  public/assets/navigation/offUser.svg
  public/assets/navigation/onHouse.svg
  public/assets/navigation/onSuitcaseRolling.svg
  public/assets/navigation/onUser.svg
  src/App.tsx
  src/core/presentation/components/TripCard.tsx
  src/core/presentation/components/auth/AuthProvider.tsx
  src/core/presentation/components/layout/Footer.tsx
  src/core/presentation/components/layout/LoginLayout.tsx
  src/core/presentation/hooks/stores/userTripStore.ts
  src/core/presentation/pages/DeleteCompletePage.tsx
  src/core/presentation/pages/Login.tsx
  src/core/presentation/pages/Mypage.tsx
  src/core/presentation/pages/Mytrips.tsx
Labels: 🖊️ feature

#48 이벤트 생성 페이지 중간 구현 완료
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/core/presentation/assets/addEventForm/calenderIcon.svg
  src/core/presentation/assets/addEventForm/dropDownIcon.svg
  src/core/presentation/assets/addEventForm/trashIcon.svg
  src/core/presentation/assets/addEventForm/xIcon.svg
  src/core/presentation/components/addEventCalenderInput/AddEventCalenderInput.tsx
  src/core/presentation/components/addEventCostInput/AddEventCostInput.tsx
  src/core/presentation/components/addEventHeader/addEventHeader.stories.tsx
  src/core/presentation/components/addEventHeader/addEventHeader.tsx
  src/core/presentation/components/addEventPostButton/AddEventPostButton.tsx
  src/core/presentation/components/addressSearchButton/addressSearchButton.tsx
  src/core/presentation/components/eventFormDropDown/EventFormDropDown.tsx
  src/core/presentation/components/eventInput/EventInput.stories.ts
  src/core/presentation/components/eventInput/EventInput.tsx
  src/core/presentation/components/layout/Layout.tsx
  src/core/presentation/components/requiredDot/RequiredDot.tsx
  src/core/presentation/hooks/event/UsePlaceSearch.tsx
  src/core/presentation/pages/AddEventPage.tsx
  src/index.css
  tailwind.config.js
Labels: 🖊️ feature

#50 refactor : routing 오류 수정
  pnpm-lock.yaml
  src/App.tsx
Labels: ♻️ refactor

#51 [일정 디테일]구글 맵 마커
  package.json
  pnpm-lock.yaml
  src/core/presentation/components/Search/SearchInputComponent.stories.tsx
  src/core/presentation/components/TripDetail.tsx
  src/core/presentation/components/createTrip/CreateTrip.tsx
  src/core/presentation/pages/TripDetailPage.tsx
Labels: 🖊️ feature

#53 Refactor/jh/2 자잘한 스타일 수정
  src/App.tsx
  src/core/presentation/components/addEventCostInput/AddEventCostInput.tsx
  src/core/presentation/components/layout/Layout.tsx
  src/core/presentation/pages/AddEventPage.tsx
  tailwind.config.js
Labels: ♻️ refactor

#52 로그아웃, 내여행페이지의 요소들 가운데 정렬 및 일부 디자인 css 변경
  src/core/presentation/components/TripCard.tsx
  src/core/presentation/components/layout/LoginLayout.tsx
  src/core/presentation/hooks/stores/userTripStore.ts
  src/core/presentation/pages/Login.tsx
  src/core/presentation/pages/Mytrips.tsx
Labels: 🚨 hotfix

#56 [여행 추가] 생성폼 멤버 추가 UX 개선 (작성자 이메일 추가) & 여행 디테일 페이지 작업
  src/core/presentation/components/TripDetail.tsx
  src/core/presentation/components/createTrip/CreateTrip.stories.ts
  src/core/presentation/components/createTrip/CreateTrip.tsx
  src/core/presentation/pages/TripDetailPage.tsx
Labels: 🖊️ feature

#62 env 따른 api url 적용되도록 수정
  src/core/presentation/components/Search/SearchInputComponent.tsx
  src/core/presentation/components/auth/AuthProvider.tsx
  src/core/presentation/components/createTrip/CreateTrip.tsx
  src/core/presentation/pages/Home.tsx
Labels: ♻️ refactor

#69 토스트 메시지 컴포넌트 생성, 브라우저 탭 문구 및 아이콘 변경
  index.html
  public/favicon2.svg
  public/vite.svg
  src/App.tsx
  src/core/presentation/components/TripCard.tsx
  src/core/presentation/components/layout/Footer.tsx
  src/core/presentation/components/ui/ToastMessageProvider.tsx
  src/core/presentation/hooks/stores/userTripStore.ts
  src/core/presentation/hooks/useToast.tsx
  src/core/presentation/pages/Login.tsx
  src/core/presentation/pages/Mypage.tsx
  src/core/presentation/pages/Mytrips.tsx
Labels: 🖊️ feature

#64 [여행 디테일] 이벤트 목록 카드 && 지도 구현
  public/assets/map/MarkerPin.svg
  src/App.tsx
  src/core/presentation/components/TripDetail/TripDetail.tsx
  src/core/presentation/components/TripDetail/eventCardList/EventCardList.tsx
  src/core/presentation/components/TripDetail/eventCardRow/EventCardRow.tsx
  src/core/presentation/components/TripDetail/map/MapWithMarkers.tsx
  src/core/presentation/components/createTrip/CreateTrip.tsx
  src/core/presentation/hooks/stores/constants.ts
  src/core/presentation/hooks/stores/googleMapsStore.ts
  src/core/presentation/hooks/useGoogleMapsLoader.ts
  src/core/presentation/pages/TripDetailPage.tsx
Labels: 🖊️ feature

#74 내 여행에서 카드 선택했을떄 해당 여행정보와 여행 이벤트 불러오도록 적용
  src/core/presentation/components/TripCard.tsx
  src/core/presentation/components/layout/Header.tsx
  src/core/presentation/components/layout/Layout.tsx
  src/core/presentation/components/ui/ToastMessageProvider.tsx
  src/core/presentation/hooks/stores/userTripEventStore.ts
  src/core/presentation/hooks/stores/userTripStore.ts
  src/core/presentation/pages/DeleteCompletePage.tsx
  src/core/presentation/pages/Mypage.tsx
  src/core/presentation/pages/Mytrips.tsx
Labels: 🖊️ feature

#75 Event 타입 엔티티 추가
  src/core/domain/entities/event.ts
Labels: 🖊️ feature

#77 [여행 디테일] 수정/삭제 기능 구현 && 지도 렌더링 문제 수정
  src/core/presentation/components/TripDetail/TripDetail.tsx
  src/core/presentation/components/TripDetail/eventCardList/EventCardList.tsx
  src/core/presentation/components/TripDetail/eventCardRow/EventCardRow.tsx
  src/core/presentation/components/TripDetail/map/MapWithMarkers.tsx
  src/core/presentation/hooks/stores/constants.ts
  src/core/presentation/hooks/stores/userTripEventStore.ts
  src/core/presentation/hooks/stores/userTripStore.ts
  src/core/presentation/pages/TripDetailPage.tsx
Labels: 🖊️ feature

#78 feature/tj/10
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/core/data/infrastructure/services/userService.ts
  src/core/presentation/components/auth/AuthProvider.tsx
  src/core/presentation/components/createTrip/CreateTrip.tsx
  src/core/presentation/components/layout/LoginLayout.tsx
  src/core/presentation/hooks/stores/userTripStore.ts
  src/core/presentation/pages/DeleteUserPage.tsx
  src/core/presentation/pages/Login.tsx
  src/core/presentation/pages/Mypage.tsx
  src/routers/ProtectedRouter.tsx
Labels: 🖊️ feature, 🚨 hotfix, ♻️ refactor

#80 [여행 디테일] 멤버 정보 가져와서 아바타 표시
  src/core/data/infrastructure/services/userService.ts
  src/core/presentation/components/TripDetail/TripDetail.tsx
Labels: 🖊️ feature

#83 Feature/jh/2 : react-hook-form으로 기능 작동및 ui 정상 작동하도록 구현
  package.json
  pnpm-lock.yaml
  public/assets/addEventForm/calenderIcon.svg
  public/assets/addEventForm/dropDownIcon.svg
  public/assets/addEventForm/trashIcon.svg
  public/assets/addEventForm/xIcon.svg
  src/core/presentation/components/addEventBottomSheetContent/AddEventBottomSheetContent.tsx
  src/core/presentation/components/addEventCalenderInput/AddEventCalenderInput.tsx
  src/core/presentation/components/addEventCostInput/AddEventCostInput.tsx
  src/core/presentation/components/addEventHeader/addEventHeader.stories.tsx
  src/core/presentation/components/addEventHeader/addEventHeader.tsx
  src/core/presentation/components/bottomSheet/BottomSheet.tsx
  src/core/presentation/components/datePicker/DatePickerComponent.tsx
  src/core/presentation/components/eventFormDropDown/EventFormDropDown.tsx
  src/core/presentation/components/eventInput/EventInput.stories.ts
  src/core/presentation/components/eventInput/EventInput.tsx
  src/core/presentation/components/scrollableTimePicker/ScrollableTimePicker.tsx
  src/core/presentation/hooks/event/UsePlaceSearch.tsx
  src/core/presentation/pages/AddEventPage.tsx
  src/index.css
Labels: 🖊️ feature

#82 state 손실 방지를 위해 persist 사용하여 tripId 및 기타 정보 로컬 스토리지에 저장
  src/core/presentation/assets/deleteCompletePage/byebye.gif
  src/core/presentation/assets/loginPage/Google Logo.svg
  src/core/presentation/assets/loginPage/backGoundImg.png
  src/core/presentation/assets/loginPage/logo-kakao.svg
  src/core/presentation/assets/loginPage/logo-naver.svg
  src/core/presentation/assets/mypage/Group.png
  src/core/presentation/assets/mypage/Group2.png
  src/core/presentation/assets/mypage/share.svg
  src/core/presentation/assets/mypage/tripIcon.png
  src/core/presentation/assets/mypage/user.svg
  src/core/presentation/assets/mytrips/tripCardImage.png
  src/core/presentation/hooks/stores/userTripEventStore.ts
Labels: 🖊️ feature

#84 [여행 디테일] google Place 적용 && CSS 수정
  src/core/presentation/components/TripDetail/TripDetail.tsx
  src/core/presentation/components/TripDetail/map/MapWithMarkers.tsx
  src/core/presentation/components/datePicker/DatePickerComponent.tsx
  src/core/presentation/hooks/stores/userTripEventStore.ts
Labels: 🖊️ feature

#85 feature : event add form 상태관리및 api 연결 완료
  package.json
  pnpm-lock.yaml
  src/core/data/infrastructure/services/eventService.ts
  src/core/presentation/components/addEventCalenderInput/AddEventCalenderInput.tsx
  src/core/presentation/components/addEventHeader/addEventHeader.tsx
  src/core/presentation/components/addEventPostButton/AddEventPostButton.tsx
  src/core/presentation/components/bottomSheet/BottomSheet.tsx
  src/core/presentation/components/eventFormDropDown/EventFormDropDown.tsx
  src/core/presentation/components/eventInput/EventInput.tsx
  src/core/presentation/components/scrollableTimePicker/ScrollableTimePicker.tsx
  src/core/presentation/pages/AddEventPage.tsx
  src/main.tsx
Labels: 🐛 bug, 🖊️ feature

#87 hotfix : add event page navigate fix
  src/core/presentation/pages/AddEventPage.tsx
Labels: 🚨 hotfix

#88 타입수정
  src/core/presentation/components/home/OngoingTrip.tsx
  src/core/presentation/components/home/TripCard.tsx
  src/core/presentation/components/home/TripList.tsx
  src/core/presentation/components/home/TripThumbnail.tsx
  src/core/presentation/pages/Home.tsx
Labels: ♻️ refactor

#89 Refactor/jh/3 : google location input 컴포넌트 분리, event submit location 주석 수정
  src/core/presentation/components/addEventGoogleLocation/AddEventGoogleLocation.tsx
  src/core/presentation/pages/AddEventPage.tsx
Labels: 🖊️ feature, ♻️ refactor

#92 [이벤트 추가] 경비 추가 버튼 클릭시 제출되는 문제 수정, CSS 수정
  src/core/presentation/components/addEventCostInput/AddEventCostInput.tsx
  src/core/presentation/components/addEventGoogleLocationInput/AddEventGoogleLocationInput.tsx
  src/core/presentation/components/addEventHeader/addEventHeader.tsx
  src/core/presentation/components/addEventPostButton/AddEventPostButton.tsx
  src/core/presentation/components/scrollableTimePicker/ScrollableTimePicker.tsx
  src/core/presentation/pages/AddEventPage.tsx
Labels: 🚨 hotfix

#101 국가이미지기본값추가
  src/core/presentation/components/home/TripThumbnail.tsx
Labels: 🖊️ feature

#105 여행 생성 페이지 스텝의 데이터 유무에 따른 버튼 색상 변경 적용
  src/core/presentation/components/createTrip/CreateTrip.tsx
  src/core/presentation/components/layout/Footer.tsx
  src/core/presentation/components/layout/Layout.tsx
  src/core/presentation/hooks/stores/authStore.ts
Labels: 🖊️ feature

#108 여행 상세 카드 및 회원탈퇴 이미지 변경
  public/assets/deleteCompletePage/bg_delPage.gif
  src/core/presentation/components/TripDetail/TripDetail.tsx
  src/core/presentation/components/layout/Layout.tsx
  src/core/presentation/pages/DeleteUserPage.tsx
Labels: 🚨 hotfix
