Repository Y-CHILDREN/client, pull requests merged in 2025-04, with the labels that each got.

#119 [이벤트 추가] 라이브러리 패키지 관리 최적화
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/core/presentation/pages/AddEventPage.tsx
  src/core/presentation/pages/UpdateEventPage.tsx
  tsconfig.app.tsbuildinfo
Labels: 🚨 hotfix

#118 feat: 토큰 저장소 로컬스토리지에서 세션스토리지로 변경, : EditTripPage컴포넌트 import .
  src/App.tsx
  src/core/presentation/components/auth/AuthProvider.tsx
  src/core/presentation/hooks/stores/authStore.ts
Labels: 🖊️ feature, 🚨 hotfix

#129 docs : client repository readme 작성
  README.md
  public/CleanArchitecture.jpg
Labels: 📜 docs
